import { useTyping } from "../../hooks/useTyping";
import { Speech } from "lucide-react";

const TypingDots = () => (
    <div style={{ display: "flex", gap: 5, alignItems: "center", padding: "4px 0" }}>
        {[0, 1, 2].map(i => (
            <div key={i} style={{
                width: 8, height: 8, borderRadius: "50%", background: "#10a37f",
                animation: `bounce 1.2s ease-in-out ${i * 0.2}s infinite`,
            }} />
        ))}
    </div>
);


function AIBubble({ content, isNew }) {
    const displayed = useTyping(isNew ? content : null);
    return (
        <div className="bubble bubble-ai">
            {isNew ? displayed : content}
        </div>
    );
}


export default function MessageList({
    messages,
    isTyping,
    bottomRef,
}) {
    return (

        <div className="message-list">
            {messages.map((msg, i) => (
                <div key={i} className={`message-row ${msg.role === "user" ? "message-row-user" : "message-row-ai"}`}>
                    {msg.role === "assistant" && <div className="avatar">< Speech size={18} /></div>}
                    <div className="message-content">
                         {msg.type === "text" && (
                            msg.role === "assistant"
                                ? <AIBubble content={msg.content} isNew={msg.isNew} />
                                : <div className="bubble bubble-user">{msg.content}</div>
                        )}
                        {msg.type === "attachment" && (
                            <div className="attach-bubble">
                                <img src={msg.content} alt={msg.filename} className="attach-img" />
                                <div className="attach-name">{msg.filename}</div>
                            </div>
                        )}

                        {msg.type === "image" && (
                            <div className="vision-result">
                                <img
                                    src={msg.content}
                                    alt="Generated result"
                                    className="vision-result-img"
                                />
                                <div className="vision-caption">
                                    Image generated by ChortGPT Vision™ 
                                </div>
                            </div>
                        )}
                    </div>
                    {msg.role === "user" && <div className="avatar avatar-user">You</div>}
                </div>
            ))}

            {isTyping && (
                <div className="message-row message-row-ai">
                    <div className="avatar">< Speech size={18} /></div>
                    <div className="bubble bubble-ai"><TypingDots /></div>
                </div>
            )}
            <div ref={bottomRef} />
        </div>


    );
}